version: "3.5"
services:
  messenger:
    image: localhost:5000/artemis-cluster:1.0-SNAPSHOT
    volumes:
      - /tmp/jgroups:/var/jgroups
      - /tmp/artemis:/var/artemis
    ports:
      # Web Server
      - 58161:8161
      # Messages
      - 61616:61616
    deploy:
      replicas: 3
      update_config:
        failure_action: continue
        order: start-first
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M

