version: "3.5"
services:
  messenger:
    image: localhost:5000/artemis-cluster:1.0-SNAPSHOT
    environment: 
      - _JAVA_OPTIONS=-Dhttp.nonProxyHosts=localhost
    volumes:
      - /var/artemis/data:/var/artemis
      - /var/artemis/jgroups:/var/jgroups
    ports:
      # Web Server
      - 58161:8161
      # Messages
      - 61616:61616
    deploy:
      replicas: 3
      update_config:
        failure_action: continue
        order: start-first
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
#
#
  producer:
    image: localhost:5000/artemis-producer:1.0-SNAPSHOT
    environment:
      - _JAVA_OPTIONS=-Dhttp.nonProxyHosts=localhost
    ports:
      - 7080:8080
    deploy:
      replicas: 3
      update_config:
        failure_action: continue
        order: start-first
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
    depends_on:
      - "messenger"
#
#
  consumer:
    image: localhost:5000/artemis-consumer:1.0-SNAPSHOT
    environment:
      - _JAVA_OPTIONS=-Dhttp.nonProxyHosts=localhost
    ports:
      - 9080:8080
    deploy:
      replicas: 3
      update_config:
        failure_action: continue
        order: start-first
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
    depends_on:
      - "messenger"