version: "3.5"
services:
  hermes_ena:
    image: localhost:5000/hermes:1.0-SNAPSHOT
    environment:
      - _JAVA_OPTIONS=-Dhttp.nonProxyHosts=localhost
    networks:
      - mount-olympus
    volumes:
      - /var/artemis/hermes_ena:/var/artemis
      - /var/artemis/jgroups:/var/jgroups
    deploy:
      update_config:
        failure_action: continue
        order: start-first
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
  #
  #
  hermes_duo:
    image: localhost:5000/hermes:1.0-SNAPSHOT
    environment:
      - _JAVA_OPTIONS=-Dhttp.nonProxyHosts=localhost
    networks:
      - mount-olympus
    volumes:
      - /var/artemis/hermes_duo:/var/artemis
      - /var/artemis/jgroups:/var/jgroups
    deploy:
      update_config:
        failure_action: continue
        order: start-first
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
  #
  #
  hermes_tria:
    image: localhost:5000/hermes:1.0-SNAPSHOT
    environment:
      - _JAVA_OPTIONS=-Dhttp.nonProxyHosts=localhost
    networks:
      - mount-olympus
    volumes:
      - /var/artemis/hermes_tria:/var/artemis
      - /var/artemis/jgroups:/var/jgroups
    deploy:
      update_config:
        failure_action: continue
        order: start-first
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
  #
  #
  themis:
    image: localhost:5000/themis:1.0-SNAPSHOT
    networks:
      - mount-olympus
    ports:
      - 8080:8080
      - 8161:8161
      - 61616:61616
    deploy:
      update_config:
        failure_action: continue
        order: start-first
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
  #
  #
  producer:
    image: localhost:5000/producer:1.0-SNAPSHOT
    environment:
      - _JAVA_OPTIONS=-Dhttp.nonProxyHosts=localhost
    networks:
      - mount-olympus
    ports:
      - 7080:8080
    deploy:
      replicas: 3
      update_config:
        failure_action: continue
        order: start-first
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
    depends_on:
      - "messenger"
  #
  #
  consumer:
    image: localhost:5000/consumer:1.0-SNAPSHOT
    environment:
      - _JAVA_OPTIONS=-Dhttp.nonProxyHosts=localhost
    networks:
      - mount-olympus
    ports:
      - 9080:8080
    deploy:
      replicas: 3
      update_config:
        failure_action: continue
        order: start-first
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
    depends_on:
      - "messenger"
#
#
networks:
  mount-olympus:
    driver: overlay
    attachable: true
